routes/web.php
Route::get('about','BrandController@about')->name('about');


Auth::routes();

Route::post('ajax/hour', 'AjaxController@hour')->name('hour');
Route::get('ajax/state',"AjaxController@state")->name('ajax.state');
Route::post('appoint/detail','AppointmentController@detail')->name('appointment.detail');

Route::post('ajax/coupon', 'CouponController@index')->name('ajax.coupon');
Route::get('ajax/coupon/remove', 'CouponController@destroy')->name('ajax.coupon.remove');

Route::group(["middleware" => ["rolecheck:user","auth"]], function () {
    Route::group(['namespace' => 'User'], function () {

        Route::get('/user-update', 'UserController@edit')->name('user.update');
        Route::post('/user-update', 'UserController@update');
        Route::get('user/appointment', 'UserController@appointment')->name('user.appointment');
    });
});

Route::get('/home', 'HomeController@index')->name('home');

Route::group(["middleware" => ["rolecheck:admin","auth"]], function () {

    Route::group(['namespace' => 'Admin'], function () {

      Route::get('admin/blog', 'BlogController@index')->name('admin.blog.index');
      Route::post('admin/blog/create', 'BlogController@create')->name('blog.create');
      Route::get('admin/blog/create', 'BlogController@create')->name('blog.create');

  Route::get('admin/blog/edit/{id}', 'BlogController@edit')->name('blog.edit');
      Route::post('admin/blog/store', 'BlogController@store')->name('admin.blog.store');
      Route::put('admin/blog/update/{id}', 'BlogController@update')->name('blog.update');
        Route::get('admin/blog/update/{id}', 'BlogController@update')->name('blog.update');
      Route::delete('admin/blog/destroy/{id}', 'BlogController@destroy')->name('blog.destroy');
      Route::post('admin/blog/status/{id}', 'BlogController@status')->name('blog.status');

      Route::post('admin/blog/image', 'BlogImageController@image_upload')->name('blog.image');
      Route::post('admin/blog/image/remove', 'BlogImageController@image_remove')->name('blog.image.remove');



        Route::resource('admin/page', 'PageController');
        Route::post('admin/page/order', 'PageController@order')->name('page.order');
        Route::get('admin/page/status/{page}', 'PageController@status')->name('page.status');

        Route::get('admin/page/{page}/home', 'PageController@home')->name('page.home');

        Route::get('admin/lang/{id}', 'Lang@index')->name('admin.lang');
        Route::resource('admin/pagecontent', 'PageContentController');
        Route::post('admin/pagecontent/order', 'PageContentController@order')->name('pagecontent.order');
        Route::get('admin/pagecontent/status/{pagecontent}', 'PageContentController@status')->name('pagecontent.status');
        Route::post('admin/pagecontetupload', 'PageContentController@contetupload')->name('contetupload.image');

        Route::resource('admin/team', 'TeamController');
        Route::post('image/team', 'TeamController@image_upload')->name('team.image');
        Route::put('image/team', 'TeamController@image_upload')->name('team.image');
        Route::post('imageremove/team', 'TeamController@image_remove')->name('team.imageremove');
        Route::post('admin/team/order', 'TeamController@order')->name('team.order');
        Route::get('admin/team/status/{team}', 'TeamController@status')->name('team.status');


        /*Route::resource('admin/sponsor', 'sponsorController');
        Route::post('image/sponsor', 'sponsorController@image_upload')->name('sponsor.image');
        Route::put('image/sponsor', 'sponsorController@image_upload')->name('sponsor.image');
        Route::post('imageremove/sponsor', 'sponsorController@image_remove')->name('sponsor.imageremove');
        Route::post('admin/sponsor/order', 'sponsorController@order')->name('sponsor.order');
        Route::get('admin/sponsor/status/{sponsor}', 'sponsorController@status')->name('sponsor.status');*/

        Route::resource('admin/setting', 'SettingController');
        Route::resource('admin/slider', 'SliderController');
        Route::post('admin/slider/order', 'SliderController@order')->name('slider.order');
        Route::get('admin/slider/status/{slider}', 'SliderController@status')->name('slider.status');

        Route::post('image/slider', 'SliderController@image_upload')->name('slider.image');
        Route::post('image/slider/remove', 'SliderController@image_remove')->name('slider.imageremove');




        Route::resource('admin/contentfile', 'ContentFileController');

        Route::post('image/contentfile', 'ContentFileController@image_upload')->name('contentfile.image');
        Route::put('image/contentfile', 'ContentFileController@image_upload')->name('contentfile.image');
        Route::post('imageremove/contentfile', 'ContentFileController@image_remove')->name('contentfile.imageremove');

        Route::resource('admin/package', 'PackageController', [
            'as' => 'admin'
        ]);
        Route::post('admin/package/order', 'PackageController@order')->name('admin.package.order');
        Route::get('admin/package/status/{package}', 'PackageController@status')->name('admin.package.status');

        Route::resource('admin/extra', 'ExtraController');
        Route::get('admin/extra/status/{extra}', 'ExtraController@status')->name('extra.status');

        Route::resource('admin/time', 'TimeController');

        Route::resource('admin/appointment', 'AppointmentController', [
            'as' => 'admin'
        ]);
        Route::get('admin/appointment/check/{appointment}', 'AppointmentController@check')->name('admin.appointment.check');

        Route::get('admin/accounting', 'AccountingController@index')->name('admin.accounting.index');
        Route::get('admin/appointmentshow/{appointment}', 'AccountingController@appointmentshow')->name('admin.accounting.appointmentshow');

        Route::get('admin/payment', 'AccountingController@paymentindex')->name('admin.accounting.paymentindex');
        Route::get('admin/paymentshow/{appointment}', 'AccountingController@paymentshow')->name('admin.accounting.paymentshow');

        Route::resource('admin/coupon', 'CouponController', [
            'as' => 'admin'
        ]);
        Route::get('admin/coupon/status/{coupon}', 'CouponController@status')->name('admin.coupon.status');

        Route::resource('admin/pagecategory', 'PageCategoryController');
        Route::post('image/pagecategory', 'PageCategoryController@image_upload')->name('pagecategory.image');
        Route::put('image/pagecategory', 'PageCategoryController@image_upload')->name('pagecategory.image');
        Route::post('imageremove/pagecategory', 'PageCategoryController@image_remove')->name('pagecategory.imageremove');
        Route::post('pdf/pagecategory', 'PageCategoryController@pdf_upload')->name('pagecategory.pdf');
        Route::put('pdf/pagecategory', 'PageCategoryController@pdf_upload')->name('pagecategory.pdf');
        Route::post('pdfremove/pagecategory', 'PageCategoryController@pdf_remove')->name('pagecategory.pdfremove');
        Route::post('admin/pagecategory/order', 'PageCategoryController@order')->name('pagecategory.order');
        Route::get('admin/pagecategory/status/{pagecategory}', 'PageCategoryController@status')->name('pagecategory.status');
          Route::get('admin/pagecategory/status/{pagecategory}', 'PageCategoryController@status')->name('pagecategorydetail.index');



        Route::resource('admin/property', 'PropertyController');
        Route::post('admin/property/order', 'PropertyController@order')->name('property.order');
        Route::get('admin/property/status/{property}', 'PropertyController@status')->name('property.status');


        Route::resource('admin/category', 'CategoryController');
        Route::post('image/category', 'CategoryController@image_upload')->name('category.image');
        Route::put('image/category', 'CategoryController@image_upload')->name('category.image');
        Route::post('imageremove/category', 'CategoryController@image_remove')->name('category.imageremove');
        Route::post('pdf/category', 'CategoryController@pdf_upload')->name('category.pdf');
        Route::put('pdf/category', 'CategoryController@pdf_upload')->name('category.pdf');
        Route::post('pdfremove/category', 'CategoryController@pdf_remove')->name('category.pdfremove');
        Route::post('admin/category/order', 'CategoryController@order')->name('category.order');
        Route::get('admin/category/status/{category}', 'CategoryController@status')->name('category.status');


        Route::resource('admin/product', 'ProductController');
        Route::post('image/product', 'ProductController@image_upload')->name('product.image');
        Route::put('image/product', 'ProductController@image_upload')->name('product.image');
        Route::post('imageremove/product', 'ProductController@image_remove')->name('product.imageremove');
        Route::post('pdf/product', 'ProductController@pdf_upload')->name('product.pdf');
        Route::put('pdf/product', 'ProductController@pdf_upload')->name('product.pdf');
        Route::post('familypdf/product', 'ProductController@familypdf_upload')->name('product.familypdf');
        Route::put('familypdf/product', 'ProductController@familypdf_upload')->name('product.familypdf');
        Route::post('pdfremove/product', 'ProductController@pdf_remove')->name('product.pdfremove');
        Route::post('admin/product/order', 'ProductController@order')->name('product.order');
        Route::get('admin/product/status/{product}', 'ProductController@status')->name('product.status');
        Route::post('admin/product/property', 'ProductController@property')->name('admin.product.property');



    });
});

Route::get('categories.html',"ProductController@categories")->name('categories');
//
Route::get('category/{slug}',"ProductController@category")->name('category');

Route::get('{slug}/{id2}-{slug2}',"ProductController@product")->name('product');

app/Http/Controllers/Admin/PageCategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\PageCategory;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Lang;
use App\Models\Setting;
use Storage;
use App\Models\Page;

use App\Http\Requests\PageCategoryPost;
use App\Http\Requests\PageCategoryImagePost;
use App\Http\Requests\PageCategoryPdfPost;


use Session;
use View;
use Intervention\Image\ImageManager;

class PageCategoryController extends Controller
{
    protected $lang;
    protected $breadcrumb;
    protected $setting;

    public function __construct()
    {
        // Fetch the Site Settings object
        $this->middleware('auth');

        $this->langs = Lang::all();
        $this->lang = Lang::where('short',\App::getLocale())->first();
        $this->setting = Setting::where('lang_id',$this->lang->id)->pluck('setting_value','setting_veriable')->all();


        $this->breadcrumb[] =array('page' => "Home",'Link' => route('home'));
        $this->breadcrumb[] =array('page' => "Page",'Link' => route('page.index'));

        View::share('langs', $this->langs);
        View::share('lang', $this->lang);
        View::share('breadcrumb', $this->breadcrumb);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $page_id = (isset($request->page_id)) ? $request->page_id : 0;
        $page = Page::find($page_id);
        $categories = PageCategory::where('page_id',$page_id)->where('lang_id',$this->lang->id)->get();

        return view('admin.pagecategory.index',compact('categories','page','page_id'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $page_id = (isset($request->page_id)) ? $request->page_id : 0 ;

        return view('admin.pagecategory.create',compact('page_id'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(PageCategoryPost $request)
    {
        //

        $result = $request->all();
        $result['lang_id'] = $this->lang->id;
        $result['status'] = 1;
        $result['order'] = 100;

        $pagecatgegory = new PageCategory;
        $pagecatgegory->create($result);

        Session::flash('status', 1);

        return redirect()->route('pagecategory.index',[null,'page_id'=>$result['page_id']]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(PageCategory $pagecategory,Request $request)
    {
        //
        $page_id = (isset($request->page_id)) ? $request->page_id : 0 ;
        return view('admin.pagecategory.edit',compact('page_id','pagecategory'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(PageCategoryPost $request, PageCategory $pagecategory)
    {
        //
        $result = $request->all();

        $pagecategory->update($result);

        Session::flash('status', 1);

        return redirect()->route('pagecategory.index',[null,'page_id'=>$pagecategory->page_id]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(PageCategory $pagecategory)
    {
        //
        $page_id = $pagecategory->page_id;
        $file= $pagecategory->image;
        if($file!=""){
            $filename = public_path().$file;
            \File::delete($filename);
        }
        $pagecategory->delete();

        return redirect()->route('pagecategory.index',[null,'page_id'=>$page_id]);
    }
    public function image_upload(PageCategoryImagePost $request)
    {
        //dd($request->all());
        if ($request->file()) {
            $path = $request->file()['upload_image'];
            $aa = Storage::put('public/pagecategory_img', $request->file()['upload_image']);
            $file = Storage::get($aa);

            $coe =$path->getClientOriginalExtension();
            $manager = new ImageManager(array('driver' => 'gd'));

            $resize = $manager->make($file);
            if($this->setting['pagecategory_image']!=""){
                $ex = explode('x',$this->setting['pagecategory_image']);
                $x = ($ex[0]==0) ? null : $ex[0];
                $y = ($ex[1]==0) ? null : $ex[1];
                $resize->resize($x,$y, function ($constraint) {
                    $constraint->aspectRatio();
                    $constraint->upsize();
                });
            }
            $resize->encode($coe);


            /* $hash = md5($resize->__toString().time());
            $path_url = "images/pagecategory_img/{$hash}.".$coe; */
            //dd(storage_path($aa));
            $resize->save(storage_path('app/'.$aa));
            $url = Storage::url($aa);

            $url;
            return array('error'=>0 ,'url'=>$url);
        }else{
            return array('error'=>1,'message' => 'error');
        }
    }
    public function image_remove(Request $request)
    {
        //dd($request->img);
        $file= $request->img;
        $filename = public_path().$file;
        \File::delete($filename);
        return array('error'=>0 ,'url'=>'https://dummyimage.com/200x200/b3b1b3/000000.png&text=Image');
    }
    public function order(Request $request)
    {
        $page_id = (isset($request->page_id)) ? $request->page_id : 0 ;

        foreach ($request->order as $key => $value) {
            if (is_numeric($value)) {
                $pagecategory = PageCategory::find($key);
                $pagecategory->order = $value;
                $pagecategory->update();
            }
        }
        Session::flash('status', 1);

        return redirect()->route('pagecategory.index',[null,'page_id'=>$page_id]);
    }
    public function status(PageCategory $pagecategory)
    {
        if ($pagecategory->status==1) {
            $pagecategory->status=0;
        } else {
            $pagecategory->status=1;
        }
        $page_id = $pagecategory->page_id;
        $pagecategory->update();
        Session::flash('status', 1);

        return redirect()->route('pagecategory.index',[null,'page_id'=>$page_id]);
    }

    public function pdf_upload(PageCategoryPdfPost $request)
    {
        //dd($request->all());
        if ($request->file()) {
            $path = $request->file()['upload_pdf'];
            $aa = Storage::put('public/pagecategory_pdf', $request->file()['upload_pdf']);
            $url = Storage::url($aa);

            $url;
            return array('error'=>0 ,'url'=>$url);
        }else{
            return array('error'=>1,'message' => 'error');
        }
    }
    public function pdf_remove(Request $request)
    {
        //dd($request->img);
        $file= $request->img;
        $filename = public_path().$file;
        \File::delete($filename);
        return array('error'=>0 ,'url'=>'https://dummyimage.com/200x200/b3b1b3/000000.png&text=Image');
    }
}

resources/views/admin/pagecategory/create.blade.php
@extends('admin.layouts.app')

@section('content')
<div class="box box-primary">
	<div class="box-header with-border">
	  <h3 class="box-title">Page Category Add</h3>
	</div>
		{!! Form::open(['route' => ['pagecategory.store' ,null,'page_id'=>$page_id], 'method' => "POST", "class" =>"smart-form", 'files' => true]) !!}

		<fieldset>
			{{ Form::dText('title','Title') }}
			{{ Form::dText('meta_desc','Meta Desc') }}
			{{ Form::dText('meta_keyword','Meta Keyword') }}
			{{ Form::dTextarea('description','Açıklama') }}

							
			{{ Form::dFile2('image','Image') }}
			{{ Form::dFile2('pdf','PDF') }}

			{{ Form::hidden('page_id', $page_id) }}
		<br/>

		</fieldset>	
		{{ Form::dSubmit('save','Insert') }}
		<br/>
	{!! Form::close() !!}


</div>

@endsection
@section('css')
<link rel="stylesheet" href="{{ asset('css/upload/jquery.fileupload.css') }}">
<style>
.input-file {
    position: relative;
    overflow: hidden;
	display: inline-block;
	
	padding: 6px 12px;
    margin-bottom: 0;
    font-size: 14px;
    font-weight: 400;
    line-height: 1.42857143;
    text-align: center;
    white-space: nowrap;
    vertical-align: middle;
    -ms-touch-action: manipulation;
    touch-action: manipulation;
    cursor: pointer;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
    background-image: none;
    border: 1px solid transparent;
	border-radius: 4px;
	color: #fff;
    background-color: #5cb85c;
    border-color: #4cae4c;
}
.input-file input {
    position: absolute;
    top: 0;
    right: 0;
    margin: 0;
    opacity: 0;
    -ms-filter: 'alpha(opacity=0)';
    font-size: 200px !important;
    direction: ltr;
    cursor: pointer;
}
</style>
@endsection
@section('js')
<script src="{{ asset('js/upload/vendor/jquery.ui.widget.js') }}"></script>
<script src="{{ asset('js/upload/jquery.iframe-transport.js') }}"></script>
<script src="{{ asset('js/upload/jquery.fileupload.js') }}"></script>
	<script >
		
			$(function () {
				'use strict';
				
				imageupload();
				$('#image_image').on('click',function() {
					$('#upload_image').trigger('click');
				});
				var i = $('#image').val();
				if (i!="") {
					$('#image_image').attr('src',i);
				}

				pdfupload();
				$('#image_pdf').on('click',function() {
					$('#upload_pdf').trigger('click');
				});
				var i = $('#pdf').val();
				if (i!="") {
					$('#image_pdf').attr('src',i);
				}
			});
			function imageupload () {
				var url = "{{ route('pagecategory.image') }}";
				$('#upload_image').fileupload({
					url: url,
					dataType: 'json',
					method: "POST",
					headers: {
							'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
						},
					done: function (e, data) {
						if (data.result.error==0) {
							var file = data.result;
							//alert(file.id);
							$('#image_image').attr('src',file.url);
							$('#image').val(file.url);
						}else{
							alert(data.result.error);
						}
					},
					progressall: function (e, data) {
						var progress = parseInt(data.loaded / data.total * 100, 10);
            			$('#progress .progress-bar').css(
                			'width',
                			progress + '%'
            			);
											
					}
				}).prop('disabled', !$.support.fileInput)
        			.parent().addClass($.support.fileInput ? undefined : 'disabled');
			}

			
			$(function () {
				$('.removeimage').on('click',function() {
					var imgpath = $('#image').val();
					
					$.ajax({
						method: "POST",
						url: "{{ route('pagecategory.imageremove') }}",
						data: { img: imgpath },
						headers: {
							'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
						}
					})
					.done(function( data ) {
						$('#image_image').attr('src',data.url);
						$('#image').val('');
					});
				});
			});

			function pdfupload () {
				var url = "{{ route('pagecategory.pdf') }}";
				$('#upload_pdf').fileupload({
					url: url,
					dataType: 'json',
					method: "POST",
					headers: {
							'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
						},
					done: function (e, data) {
						if (data.result.error==0) {
							var file = data.result;
							//alert(file.id);
							$('#image_pdf').attr('src',file.url);
							$('#pdf').val(file.url);
						}else{
							alert(data.result.error);
						}
					},
					progressall: function (e, data) {
						var progress = parseInt(data.loaded / data.total * 100, 10);
            			$('#progress .progress-bar').css(
                			'width',
                			progress + '%'
            			);
											
					}
				}).prop('disabled', !$.support.fileInput)
        			.parent().addClass($.support.fileInput ? undefined : 'disabled');
			}

			$(function () {
				$('.removepdf').on('click',function() {
					var imgpath = $('#pdf').val();
					
					$.ajax({
						method: "POST",
						url: "{{ route('pagecategory.pdfremove') }}",
						data: { img: imgpath },
						headers: {
							'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
						}
					})
					.done(function( data ) {
						$('#image_pdf').attr('src',data.url);
						$('#pdf').val('');
					});
				});
			});
			
	</script>
		<link rel="stylesheet" href="{{ asset('admin/css/bootstrap-multiselect.css') }}" type="text/css">
		<script type="text/javascript" src="{{ asset('admin/js/bootstrap-multiselect.js') }}"></script>
		<script>
		$(document).ready(function() {
			$('#lists').multiselect({
				buttonClass: 'form-control',
				  buttonWidth: '100%',
				  buttonText: function(options) {
					if (options.length == 0) {
						return 'None selected';
					}
					else if (options.length > 999) {
						return options.length + ' selected ';
					}
					else {
						var selected = '';
						options.each(function() {
							selected += $(this).text() + ', ';
						});
						return selected.substr(0, selected.length -2) + '';
					}
				},
			});
		});
		</script>


<!-- Include CSS for icons. -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
 
<!-- Include Editor style. -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.5.1/css/froala_editor.pkgd.min.css" rel="stylesheet" type="text/css" />
<link href="https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.5.1/css/froala_style.min.css" rel="stylesheet" type="text/css" />
 
<!-- Create a tag that we will use as the editable area. -->
<!-- You can use a div tag as well. -->
 

 
<!-- Include Editor JS files. -->
<script type="text/javascript" src="{{ asset('admin/js/froala/froala_editor.pkgd.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('admin/js/froala/plugins/image_manager.min.js') }}"></script>
<!-- Initialize the editor. -->
<script>
	
  $(function() {
	$.FroalaEditor.DefineIcon('btn-rows', {NAME: 'plus'});
	$.FroalaEditor.RegisterCommand('btn-rows', {
		title: 'Advanced options',
		type: 'dropdown',
		focus: true,
		  undo: true,
		  refreshAfterCallback: true,

	});
	$('#description').froalaEditor({
		heightMin: 500,
		toolbarButtons: ['fullscreen', 'bold', 'italic', 'underline', 'strikeThrough', 'subscript', 'superscript', '|', 'fontFamily', 'fontSize', 'color', 'inlineStyle', 'paragraphStyle', '|', 'paragraphFormat', 'align', 'formatOL', 'formatUL', 'outdent', 'indent', 'quote', '-', 'insertLink', 'insertImage', 'insertVideo', 'embedly', 'insertFile', 'insertTable', '|', 'emoticons', 'specialCharacters', 'insertHR', 'selectAll', 'clearFormatting', '|', 'print', 'spellChecker', 'help', 'html', '|', 'undo', 'redo','|','btn-rows'],
		// Set the image upload parameter.
		imageUploadParam: 'image_param',

		// Set the image upload URL.
		imageUploadURL: "{{ route('contetupload.image') }}",

		// Additional upload params.
		imageUploadParams: {id: 'my_editor'},
		requestHeaders: {
			'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('description')
		},

		// Set request type.
		imageUploadMethod: 'POST',

		// Set max image size to 5MB.
		imageMaxSize: 5 * 1024 * 1024,

		// Allow to upload PNG and JPG.
		imageAllowedTypes: ['jpeg', 'jpg', 'png']
		})
		.on('froalaEditor.image.beforeUpload', function (e, editor, images) {
		// Return false if you want to stop the image upload.
		})
		.on('froalaEditor.image.uploaded', function (e, editor, response) {
		// Image was uploaded to the server.
		})
		.on('froalaEditor.image.inserted', function (e, editor, $img, response) {
		// Image was inserted in the editor.
		})
		.on('froalaEditor.image.replaced', function (e, editor, $img, response) {
		// Image was replaced in the editor.
		})
		.on('froalaEditor.image.error', function (e, editor, error, response) {
		// Bad link.
		/*if (error.code == 1) { ... }

		// No link in upload response.
		else if (error.code == 2) { ... }

		// Error during image upload.
		else if (error.code == 3) { ... }

		// Parsing response failed.
		else if (error.code == 4) { ... }

		// Image too text-large.
		else if (error.code == 5) { ... }

		// Invalid image type.
		else if (error.code == 6) { ... }

		// Image can be uploaded only to same domain in IE 8 and IE 9.
		else if (error.code == 7) { ... }*/

		// Response contains the original server response to the request if available.
	
	})
  });
</script>
@endsection

resources/views/admin/pagecategory/index.blade.php
@extends('admin.layouts.app')

@section('content')
<div class="content">
	<div class="row">
		<div class="col-md-12">
			<div class="row">
				<div class="col-md-12">
					<a class="btn btn-primary" href="{{ route('pagecategory.create',[Null,'page_id'=>$page_id]) }}" style="float: right;margin: 10px 0px;">Add</a>
					
				</div>
			</div>
			<div class="box">
				<div class="box-header with-border">
				<h3 class="box-title">Category</h3>
			</div>
			<div class="box-body">
						{!! Form::open(['route' => ['pagecategory.order', Null,  'page_id' => $page_id], 'method' => "POST"]) !!}

					<table class="table table-bordered">
						<thead>
							<tr>
								<th>Short NO</th>
                        		<th>Title</th>
                        		<th style="width: 10px;">Status</th>
                        		<th>Action</th>
                        	</tr>
                      	</thead>

						@if ($categories)
							<tbody>
								@foreach ($categories as $category)
									<tr>
										<td style="width: 50px;">{{ Form::dText2('order['.$category->id.']','',null,$category->order,['style'=> 'width: 50px;text-align: center;']) }}</td>
									
										<td><a href="{{ route('pagecategory.index', ['page_id'=>$page->id,'pagecategory_id'=>$category->id] ) }}" >{{ $category->title }}</a></td>
										<td style="text-align: center;">
											<a href="{{ route('pagecategory.status', ['id'=>$category->id] ) }}">@if ($category->status==1) <i class="fa fa-eye" style="color:#356635;    font-size: 19px;"></i> @else <i class="fa fa-eye-slash" style="color:red;font-size: 19px;"></i> @endif</a>
										</td>
										<td>
											<a href="{{ route('pagecategory.index', ['page_id'=>$page->id,'pagecategory_id'=>$category->id] ) }}" class="btn btn-primary action"><i class="fa fa-list"></i></a>
											<a href="{{ route('pagecontent.index', [null,'type' => $page->page_type_id,'oid'=>$category->id]) }}" class="btn btn-primary action"><i class="fa fa-file"></i></a>
											<a href="{{ route('pagecategory.edit', ['id'=>$category->id, 'page_id' => $page_id]) }}" class="btn btn-primary action">Edit</a>
											<a href="{{ route('pagecategory.destroy', ['id'=>$category->id, 'page_id' => $page_id ]) }}" data-method="delete" data-token="{{csrf_token()}}" data-confirm="Are you sure it will be deleted?" class="btn btn-danger action">Delete</a>
										</td>
									</tr>
								@endforeach
								<tr>
									<td>{{ Form::dSubmit('save','Short Save') }}</td>
									<td colspan="4"></td>
								</tr>
							</tbody>
						@endif
					</table>
					{!! Form::close() !!}

			
				</div>
			</div>
		</div>
	</div>	
</div>
@endsection